# -*- coding: utf-8 -*-
"""Model deployment using fastapi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xeqgm2mx4_4GLzwsFJ-0BiN_7EoJSYa9
"""

!pip install spacy-transformers

pip install fitz

!pip install transformers

pip install ipython



pip install PyMuPDF

import spacy, fitz,io
import pathlib

print("Loading Resume Parser model...")
nlp = spacy.load('/content/drive/MyDrive/Model for 1panel/assets/ResumeModel/output/model-best')
print("Resune Parser model loaded")

import csv
with open('/content/Sample data.csv', newline='') as csvfile:
 spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
 for row in spamreader:
   print(', '.join(row))

print("Resume taken as input")

text_of_resume = " "

text_of_resume = text_of_resume +str(row)
print(text_of_resume)

label_list=[]
text_list = []
dic = {}

doc = nlp(str(row))
print(doc.ents)
for ent in doc.ents:
 label_list.append(ent.label_)
 text_list.append(ent.text)
print("Model work done")
print(doc)
print(label_list)
print(text_list)

for i in range(len(label_list)):
 if label_list[i] in dic:
 # if the key already exists, append the new value to the list of values
  dic[label_list[i]].append(text_list[i])
 else:
 # if the key does not exist, create a new key-value pair
  dic[label_list[i]] = [text_list[i]]

print(dic)
resume_data_annotated = ''
for key, value in dic.items():
 for val in value:
  resume_data_annotated += val + " "

